version: 2
jobs:
  # build docker image, push to gcr.
  deploy:
    # https://circleci.com/docs/2.0/building-docker-images/
    docker:
      - image: docker:git
    environment:
      - REPOSITORY: rnidev/mysql56-barracuda
    steps:
      - checkout
      - setup_remote_docker:
          # FIXME: needs change of plan
          # https://circleci.com/docs/2.0/docker-layer-caching/
          docker_layer_caching: true
      - run:
          name: build latest
          command: docker build -t $REPOSITORY .
      - run:
          # HACK: Using circleci build num as tag
          # TODO: set proper tag
          name: tag
          command: docker tag $REPOSITORY $REPOSITORY:$CIRCLE_BUILD_NUM
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push latest
          command: docker push $REPOSITORY
      - run:
          name: push tagged
          command: docker push $REPOSITORY:$CIRCLE_BUILD_NUM
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: code-common
          filters:
            branches:
              only: master
